version: "0.5"
is_strict: true
processes:
  servicebus-emulator:
    command: docker compose up -d --remove-orphans
    is_daemon: true
    launch_timeout_seconds: 10
    availability:
      restart: "no"
    readiness_probe:
      http_get:
        host: 127.0.0.1
        port: 5300
        path: /health
      initial_delay_seconds: 2
      period_seconds: 2
      timeout_seconds: 2
      failure_threshold: 90
    shutdown:
      command: docker compose down --volumes --remove-orphans
      timeout_seconds: 30
  servicebus-logs:
    command: docker compose logs --follow
    disabled: true
    availability:
      restart: "no"
    depends_on:
      servicebus-emulator:
        condition: process_healthy
  example:
    command: python examples/basic.py
    disabled: true
    availability:
      restart: "no"
      exit_on_end: true
    depends_on:
      servicebus-emulator:
        condition: process_healthy
  example-request-reply:
    command: python examples/request_reply.py
    disabled: true
    availability:
      restart: "no"
      exit_on_end: true
    depends_on:
      servicebus-emulator:
        condition: process_healthy
  example-messagepack:
    command: python examples/messagepack.py
    disabled: true
    availability:
      restart: "no"
      exit_on_end: true
    depends_on:
      servicebus-emulator:
        condition: process_healthy
  tests:
    command: pytest -n 2
    disabled: true
    availability:
      restart: "no"
      exit_on_end: true
    depends_on:
      servicebus-emulator:
        condition: process_healthy
  test-coverage:
    command: pytest -n 2 --cov --cov-report=term --cov-report=html
    disabled: true
    availability:
      restart: "no"
      exit_on_end: true
    depends_on:
      servicebus-emulator:
        condition: process_healthy
